name: Generate Token

on:
  workflow_dispatch:
    inputs:
      sub:
        description: 'Subscription name'
        required: true
        default: 'xray'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        run: |
          SECRET="${{ secrets.SECRET }}"
          # Calculate expiration: 3 days (3*24*60*60 seconds)
          EXP=$(($(date +%s) + 259200))
          PAYLOAD="{\"sub\": \"${{ github.event.inputs.sub }}\", \"exp\": $((EXP * 1000))}"
          PAYLOAD_B64=$(echo -n "$PAYLOAD" | base64 | tr -d '=' | tr '/+' '_-')
          SIGNATURE=$(echo -n "$PAYLOAD_B64" | openssl dgst -sha256 -hmac "$SECRET" -binary | base64 | tr -d '=' | tr '/+' '_-')
          echo "Your Token URL:"
          echo "https://YOUR_WORKER_URL.workers.dev/?token=${PAYLOAD_B64}.${SIGNATURE}"
