name: clash-meta + amnezia

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List directory contents
        run: |
          ls -R assets
          cat assets/requirementsyml.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          architecture: x64

      # Creating a cache for increased speed and performance, also saving resources
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip || exit 1
          pip install -r assets/requirementsyml.txt || exit 1
       
      # Run ;⁠)
      - name: Run config generation script
        run: |
          python assets/generate-clash.py 2>&1 || { echo "Script failed with exit code $?"; exit 1; }

      - name: Commit and push config files
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "actions@github.com"
                    
          if git status --porcelain | grep -q "clash-wg.yml" || git status --porcelain; then
            echo "Changes detected. Committing and pushing."
            git add clash-wg.yml
            git commit -m "Auto: Update clash-wg configurations at: $(TZ='Asia/Tehran' date '+%H:%M:%S')" -m "Wireguard private key, addresses, reserved, and all IPs have been renewed"
            git -c committer.name="darknessm427" -c committer.email="171773043+darknessm427@users.noreply.github.com" push
          else
            echo "No changes detected in config files."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
