name: Generate Secure JWT Tokens

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:

jobs:
  build-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install jsonwebtoken

      - name: Generate JWT tokens
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: node build-jwt.js

      - name: Commit tokens.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tokens.json
          git commit -m "🛡️ Auto-update of secure JWT tokens"
          git push
